"""add event created_by ownership

Revision ID: fde91fffb2e2
Revises: 49db0218368d
Create Date: 2026-08-17 13:42:25.040762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde91fffb2e2'
down_revision: Union[str, Sequence[str], None] = '49db0218368d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('events', sa.Column('created_by', sa.UUID(), nullable=True))
    # Named explicitly (rather than the autogenerated `None`, which lets
    # Postgres pick a default name) because `downgrade()` needs a concrete
    # name to drop -- there's no naming convention configured on `Base`
    # to make autogenerate infer one automatically. Matches the name
    # Postgres itself assigns by default (`<table>_<column>_fkey`), so
    # this doesn't change what gets created, only makes it drop cleanly.
    op.create_foreign_key(
        'events_created_by_fkey', 'events', 'profiles', ['created_by'], ['id'], ondelete='SET NULL'
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('events_created_by_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'created_by')
