"""add profile last_name and parent_role

Revision ID: fecdb3c7a299
Revises: f4c9d2a7e105
Create Date: 2026-09-06 23:58:52.630052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fecdb3c7a299'
down_revision: Union[str, Sequence[str], None] = 'f4c9d2a7e105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('parent_role', sa.Enum('mother', 'father', 'guardian', 'prefer_not_to_say', name='parentrole', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'parent_role')
    op.drop_column('profiles', 'last_name')
    # ### end Alembic commands ###
